version: '3'

services:
  apt-mirror:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/config.json
      - ./cache:/app/cache
    restart: unless-stopped 